### ISSUE TITLE
Error port disabled

### ISSUE THREAD

**Issue by rezzalex** [CreasolTech/CreasolDomBus#2]
Hello Paolo,

for the first time after 1 year of usage, I have enable the error logs for this plugin; here is the error : 

> 2024-01-08 09:22:05.813 Error: dombus: Call to function 'onStart' failed, exception details:
> 2024-01-08 09:22:05.852 Error: dombus: Traceback (most recent call last):
> 2024-01-08 09:22:05.856 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/CreasolDomBusProtocol.py", line 264, in portsDisabledInit
> 2024-01-08 09:22:05.856 Error: dombus: fd=open(PORTSDISABLED)
> 2024-01-08 09:22:05.856 Error: dombus: FileNotFoundError: [Errno 2] No such file or directory: 'plugins/CreasolDomBus/portsDisabled.json'
> 2024-01-08 09:22:05.856 Error: dombus:
> 2024-01-08 09:22:05.856 Error: dombus: During handling of the above exception, another exception occurred:
> 2024-01-08 09:22:05.856 Error: dombus:
> 2024-01-08 09:22:05.856 Error: dombus: Traceback (most recent call last):
> 2024-01-08 09:22:05.856 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/plugin.py", line 172, in onStart
> 2024-01-08 09:22:05.856 Error: dombus: _plugin.onStart()
> 2024-01-08 09:22:05.856 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/plugin.py", line 82, in onStart
> 2024-01-08 09:22:05.856 Error: dombus: dombus.portsDisabledInit()
> 2024-01-08 09:22:05.856 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/CreasolDomBusProtocol.py", line 269, in portsDisabledInit
> 2024-01-08 09:22:05.856 Error: dombus: portsDisabledWriteNow()
> 2024-01-08 09:22:05.856 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/CreasolDomBusProtocol.py", line 257, in portsDisabledWriteNow
> 2024-01-08 09:22:05.856 Error: dombus: with open(PORTSDISABLED, 'w') as fd:
> 2024-01-08 09:22:05.856 Error: dombus: FileNotFoundError: [Errno 2] No such file or directory: 'plugins/CreasolDomBus/portsDisabled.json'

Do we need a portsDisabled.json file ? What should be its role and purpose ?

**Comment by CreasolTech** [comment]
Please type the following commands from linux shell:

```
cd /opt/domoticz/userdata/plugins/CreasolDomBus
ls -al
ps aux|grep domoticz
```

and write here the result.
I have to know why plugin cannot write the portsDisabled.json file in that directory.
For any DomBus module it's possible to add, in the device description, 
DISABLE=1,4,5,7,9
to disable the selected ports.
This is useful when, in the same bus, are connected 15 DomBus modules or more, because the python plugin manages max 255 devices, so with DISABLE= command it's possible to disable unused ports and install more modules.
Thanks.
P.S.: how does it work the EVSE module to charge your EV car?

**Comment by rezzalex** [comment]
Here it is : 
![image](https://github.com/CreasolTech/CreasolDomBus/assets/35136439/975efe19-b08b-4678-9615-a802680f189d)

**Comment by rezzalex** [comment]
Solved the problem by adding the specific plugin filepath when running DZ in Docker

`PORTSDISABLED="/opt/domoticz/userdata/plugins/CreasolDomBus/portsDisabled.json"
`

**Comment by daserra23** [comment]
I have the same issue when running dombus plugin inside a docker container. Where did you add this line ?

**Comment by CreasolTech** [comment]
in the file CreasolDomBusProtocol.py
`PORTSDISABLED="plugins/CreasolDomBus/portsDisabled.json"`

**Comment by daserra23** [comment]
Thanks for your reply. That line is already in CreasolDomBusProtocol.py and I am giving up on domoticz in docker.
