### ISSUE TITLE
Another Error

### ISSUE THREAD

**Issue by rezzalex** [CreasolTech/CreasolDomBus#3]
> 2024-01-08 21:13:46.392 Error: dombus: Call to function 'onMessage' failed, exception details:
> 2024-01-08 21:13:46.651 Error: dombus: Traceback (most recent call last):
> 2024-01-08 21:13:46.651 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/plugin.py", line 185, in onMessage
> 2024-01-08 21:13:46.651 Error: dombus: _plugin.onMessage(Connection, Data)
> 2024-01-08 21:13:46.653 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/plugin.py", line 104, in onMessage
> 2024-01-08 21:13:46.653 Error: dombus: dombus.decode(Devices)
> 2024-01-08 21:13:46.654 Error: dombus: File "/opt/domoticz/userdata/plugins/CreasolDomBus/CreasolDomBusProtocol.py", line 1058, in decode
> 2024-01-08 21:13:46.654 Error: dombus: if frameLen<=FRAME_LEN_MAX or (rxbuffer[FRAME_HEADER2]==0x09 and rxbuffer[FRAME_HEADER2+1]==0xff): # waiting for DomBus txConfig()
> 2024-01-08 21:13:46.654 E rror: dombus: IndexError: bytearray index out of range

**Comment by CreasolTech** [comment]
This is not a real problem: sometimes serial data is received corrupted, and in that case you see that error.
I can modify the source to hide it, but I prefer that error is logged.
DomBus modules retry sending frame that did not receive an acknowledge, so the protocol is safe.
Thanks for reporting.
